chore: add formatter (#61)
* feat: add prettier and pre-commit hook

* chore: add formatter to CI

* chore: add linter to pre-commit hook

* Update package-lock

* Run formatter

---------

Co-authored-by: Zach Fedor <zachfedor@gmail.com>

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -2,7 +2,7 @@ name: Build and Test
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
 
 env:
@@ -13,12 +13,12 @@ env:
 jobs:
   build:
     strategy:
-        fail-fast: true
+      fail-fast: true
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v3
-      with:
+      - uses: actions/checkout@v4
+      - uses: actions/cache@v3
+        with:
           path: |
             ~/.cargo/bin/
             runner/.cargo/bin/
@@ -27,24 +27,25 @@ jobs:
             ~/.cargo/git/db/
             target/
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-    - run: rustup target add wasm32v1-none
-    - uses: stellar/quickstart@main
-      with:
-        tag: testing
-    - run: sudo apt-get update && sudo apt-get install -y libudev-dev libdbus-1-dev pkg-config
-    - name: Check for stellar-scaffold binary
-      run: |
-        if ! command -v stellar-scaffold &> /dev/null; then
-          echo "stellar-scaffold not found, installing..."
-          cargo install --git https://github.com/ahalabs/scaffold-stellar --branch main stellar-scaffold-cli
-        else
-          echo "stellar-scaffold already installed. Clear cache to force reinstall."
-        fi
-    - name: Build clients before building the project
-      run: STELLAR_SCAFFOLD_ENV=development stellar-scaffold build --build-clients
-    - run: npm ci
-    - run: npm run install:contracts
-    - run: npm run build
-    - run: npm run lint
-    - name: Run tests
-      run: npm test --if-present
+      - run: rustup target add wasm32v1-none
+      - uses: stellar/quickstart@main
+        with:
+          tag: testing
+      - run: sudo apt-get update && sudo apt-get install -y libudev-dev libdbus-1-dev pkg-config
+      - name: Check for stellar-scaffold binary
+        run: |
+          if ! command -v stellar-scaffold &> /dev/null; then
+            echo "stellar-scaffold not found, installing..."
+            cargo install --git https://github.com/ahalabs/scaffold-stellar --branch main stellar-scaffold-cli
+          else
+            echo "stellar-scaffold already installed. Clear cache to force reinstall."
+          fi
+      - name: Build clients before building the project
+        run: STELLAR_SCAFFOLD_ENV=development stellar-scaffold build --build-clients
+      - run: npm ci
+      - run: npm run install:contracts
+      - run: npm run build
+      - run: npm run lint
+      - run: npx prettier . --check
+      - name: Run tests
+        run: npm test --if-present
